export const BOARD_LAYOUT = [
  // Cạnh dưới (từ ô 0 đến 7) - 8 ô
  {
    id: 0,
    name: "Bắt Đầu",
    type: "corner",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "start",
  },
  {
    id: 1,
    name: "Thành Cổ Loa",
    type: "land",
    group: "purple",
    price: 60,
    rent: [2, 10, 30, 90, 160],
    buildCost: 50,
    iconKey: "co_loa",
  },
  {
    id: 2,
    name: "Sự Kiện",
    type: "special",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "event",
  },
  {
    id: 3,
    name: "Làng Hy Cương",
    type: "land",
    group: "purple",
    price: 60,
    rent: [4, 20, 60, 180, 320],
    buildCost: 50,
    iconKey: "hy_cuong",
  },
  {
    id: 4,
    name: "Thuế Thu Nhập",
    type: "tax",
    group: null,
    price: 200,
    rent: [],
    buildCost: 0,
    iconKey: "tax",
  },
  {
    id: 5,
    name: "Sông Hồng",
    type: "water",
    group: "transport",
    price: 200,
    rent: [25, 50, 100, 200],
    buildCost: 0,
    iconKey: "song_hong",
  },
  {
    id: 6,
    name: "Làng Đông Sơn",
    type: "land",
    group: "lightBlue",
    price: 100,
    rent: [6, 30, 90, 270, 400],
    buildCost: 50,
    iconKey: "dong_son",
  },
  {
    id: 7,
    name: "Làng Đồng Cổ",
    type: "land",
    group: "lightBlue",
    price: 120,
    rent: [8, 40, 100, 300, 450],
    buildCost: 50,
    iconKey: "dong_co",
  },

  // Cạnh trái (từ ô 8 đến 15) - 8 ô
  {
    id: 8,
    name: "Nhà Tù",
    type: "corner",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "prison",
  },
  {
    id: 9,
    name: "Chùa Hội Phước",
    type: "land",
    group: "pink",
    price: 140,
    rent: [10, 50, 150, 450, 625],
    buildCost: 100,
    iconKey: "hoi_phuoc",
  },
  {
    id: 10,
    name: "Điện Lực",
    type: "utility",
    group: "utility",
    price: 150,
    rent: [],
    buildCost: 0,
    iconKey: "electric",
  },
  {
    id: 11,
    name: "Địa đạo Củ Chi",
    type: "land",
    group: "pink",
    price: 140,
    rent: [10, 50, 150, 450, 625],
    buildCost: 100,
    iconKey: "cu_chi",
  },
  {
    id: 12,
    name: "Sông Bến Hải",
    type: "water",
    group: "transport",
    price: 200,
    rent: [25, 50, 100, 200],
    buildCost: 0,
    iconKey: "song_ben_hai",
  },
  {
    id: 13,
    name: "Điện Biên Phủ",
    type: "land",
    group: "orange",
    price: 180,
    rent: [14, 70, 200, 550, 750],
    buildCost: 100,
    iconKey: "dien_bien_phu",
  },
  {
    id: 14,
    name: "Sự Kiện",
    type: "special",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "event",
  },
  {
    id: 15,
    name: "Chùa Thạch Long",
    type: "land",
    group: "orange",
    price: 200,
    rent: [16, 80, 220, 600, 800],
    buildCost: 100,
    iconKey: "thach_long",
  },

  // Cạnh trên (từ ô 16 đến 23) - 8 ô
  {
    id: 16,
    name: "Bãi Đậu Xe",
    type: "corner",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "free_parking",
  },
  {
    id: 17,
    name: "Chùa Một Cột",
    type: "land",
    group: "red",
    price: 220,
    rent: [18, 90, 250, 700, 875],
    buildCost: 150,
    iconKey: "mot_cot",
  },
  {
    id: 18,
    name: "Khí Vận",
    type: "special",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "chance",
  },
  {
    id: 19,
    name: "Thành Thăng Long",
    type: "land",
    group: "red",
    price: 220,
    rent: [18, 90, 250, 700, 875],
    buildCost: 150,
    iconKey: "thang_long",
  },
  {
    id: 20,
    name: "Sông Như Nguyệt",
    type: "water",
    group: "transport",
    price: 200,
    rent: [25, 50, 100, 200],
    buildCost: 0,
    iconKey: "song_nhu_nguyet",
  },
  {
    id: 21,
    name: "Chùa Thiên Mụ",
    type: "land",
    group: "yellow",
    price: 260,
    rent: [22, 110, 330, 800, 975],
    buildCost: 150,
    iconKey: "thien_mu",
  },
  {
    id: 22,
    name: "Cấp Nước",
    type: "utility",
    group: "utility",
    price: 150,
    rent: [],
    buildCost: 0,
    iconKey: "water_work",
  },
  {
    id: 23,
    name: "Kinh thành Huế",
    type: "land",
    group: "yellow",
    price: 280,
    rent: [24, 120, 360, 850, 1025],
    buildCost: 150,
    iconKey: "kinh_thanh_hue",
  },

  // Cạnh phải (từ ô 24 đến 31) - 8 ô
  {
    id: 24,
    name: "Vào Tù",
    type: "corner",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "go_to_jail",
  },
  {
    id: 25,
    name: "Thuận Thành",
    type: "land",
    group: "green",
    price: 300,
    rent: [26, 130, 390, 900, 1100],
    buildCost: 200,
    iconKey: "thuan_thanh",
  },
  {
    id: 26,
    name: "Thành Đại La",
    type: "land",
    group: "green",
    price: 320,
    rent: [28, 150, 450, 1000, 1200],
    buildCost: 200,
    iconKey: "dai_la",
  },
  {
    id: 27,
    name: "Sự Kiện",
    type: "special",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "event",
  },
  {
    id: 28,
    name: "Sông Bạch Đằng",
    type: "water",
    group: "transport",
    price: 200,
    rent: [25, 50, 100, 200],
    buildCost: 0,
    iconKey: "song_bach_dang",
  },
  {
    id: 29,
    name: "Khí Vận",
    type: "special",
    group: null,
    price: 0,
    rent: [],
    buildCost: 0,
    iconKey: "chance",
  },
  {
    id: 30,
    name: "Chùa Dâu",
    type: "land",
    group: "darkBlue",
    price: 350,
    rent: [35, 175, 500, 1100, 1300],
    buildCost: 200,
    iconKey: "chua_dau",
  },
  {
    id: 31,
    name: "Thuế Đặc Biệt",
    type: "tax",
    group: null,
    price: 100,
    rent: [],
    buildCost: 0,
    iconKey: "luxury_tax",
  },
];
// Cấu hình cho các loại ô
export const SQUARE_TYPES = {
  land: {
    topShape: "nui", // Hình núi cho ô đất
    textColor: "#FFFFFF",
  },
  water: {
    topShape: "song", // Hình sóng cho ô nước
    textColor: "#FFFFFF",
  },
  special: {
    textColor: "#000000",
  },
  corner: {
    textColor: "#FFFFFF",
  },
};

// Cấu hình màu sắc cho các nhóm ô
export const COLOR_GROUPS = {
  purple: 0x9370db, // Cạnh dưới
  blue: 0x4682b4, // Cạnh phải
  green: 0x228b22, // Cạnh trên
  red: 0xcd5c5c, // Cạnh trái
};
